security:
  enable_authenticator_manager: true

  providers:
    app_user_provider:
      memory: ~

    # providers:
    #     app_user_provider:
    #         memory:
    #             users:
    #                 user:
    #                     password: null
    #                     roles: ['ROLE_USER']


  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # üîì Firewall public : pas de s√©curit√© pour /
    public:
        pattern: ^/$
        security: false

    # üîê Firewall principal prot√©g√© par CAS
    main:
      pattern: ^/
      lazy: true
      provider: app_user_provider
      custom_authenticators:
        - App\Security\CasAuthenticator
      logout:
        path: /logout
        target: /

  access_control:
    # Autoriser tout le monde sur la page d'accueil
    - { path: ^/$, roles: PUBLIC_ACCESS }
    # Prot√©ger tout le reste
    - { path: ^/.*, roles: ROLE_USER }

    # - { path: ^/hello, roles: ROLE_USER }
    # - { path: ^/, roles: PUBLIC_ACCESS }
    # - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
