services:


    App\Controller\:
        resource: '../src/Controller/'
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']


    App\Security\CasAuthenticator:
        arguments:
            $router: '@router'
        tags:
            - { name: 'monolog.logger' } # optionnel


