services:


    App\Controller\PublicController:
        public: true
        tags: ['controller.service_arguments']

    App\Security\CasAuthenticator:
        arguments:
            $router: '@router'
        tags:
            - { name: 'monolog.logger' } # optionnel


