services:


    App\Controller\:
        resource: '../src/Controller/'
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']


    App\Security\CasAuthenticator:
        autowire: true
        autoconfigure: true


