services:

    App\Controller\:
        resource: '../src/Controller/'
        autowire: true
        autoconfigure: true

    App\Security\CasAuthenticator:
        autowire: true
        autoconfigure: true


